jwt.public.key=classpath:public.key
jwt.private.key=classpath:private.key

spring.application.name=gerenciamento-ordem-de-servico

# Conexão PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ordem-servico
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Geração do script SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Geração do schema
#spring.jpa.properties.hibernate.hbm2ddl.auto=create
#spring.jpa.properties.hibernate.hbm2ddl.schema_generation.scripts.action=create
#spring.jpa.properties.hibernate.hbm2ddl.schema_generation.scripts.create-target=src/main/resources/schema.sql
